### ISSUE TITLE
Explore page v1

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#128]
![explore_v1](https://cloud.githubusercontent.com/assets/1657444/20657653/8a019bf4-b505-11e6-9519-d23bd1005c00.png)

The idea is for trackables (of all types) to have their own page with stats about their correlation to other trackables. Understanding how to treat chronic illness is all about correlations -- between environment and symptoms, between treatments and conditions, etc.

@Graydyn has already created an API for stats like this, and can help with additional endpoints needed.

The bars showing the percentage of {{current trackable}} users tracking {{related trackable}} are not necessarily MVP but are very nice for helping to visualize the relative quantities.

A future V2 could include stats about the current user, user opinions (ratings) of overall treatment effectiveness, ability to add the current trackable to check in, and other population-wide stats.

**Comment by lmerriam** [comment]
Here's a mock of a basic top-level "Explore" page:
![explore_v1_search](https://cloud.githubusercontent.com/assets/1657444/21361917/1e2d3bca-c6b4-11e6-802a-9d52f50b4916.png)

It's fairly self-explanatory but the major points are:
- Search across the different trackable types using the same standard input that we use to find trackables in the check-in. No separate template needed for results, they simply show up in the ember-power-select dropdown and the user selects one.
- Link to popular trackables in each category to give users a starting point. A nice stretch goal would be to randomize them a bit per session so this page isn't always exactly the same -- maybe selecting a random set from the top 100 of each type.
- In the base state display only three of each type of trackable, and allow the user to expand the card to see something like 10. Eventually we can have all sorts of subsections for each trackable type with more detailed info, but we'll keep the complexity down for v1.

**Comment by jaredgalanis** [comment]
I’m working through the top level explore page right now. One thing I am noticing is that our power select drop down (and related searches/queries) that allows searching/selecting a trackable is built to take one trackable at a time. The above mock contemplates the select including all trackables in the select. Per discussion with @lmerriam just now, the most desirable/quickest thing for the MVP of this feature would be to break out a select for each trackable type - so that's how I'll handle it unless anyone else feels strongly otherwise.

**Comment by lmerriam** [comment]
Closing in favor of #145 which includes more advanced analysis of effects
