### ISSUE TITLE
History visual update

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#136]
We want to update the the history design so the data is easier to read, with better contrast and clearer separation between different charts.

<img width="418" alt="screenshot 2016-12-23 00 21 20" src="https://cloud.githubusercontent.com/assets/1657444/21449862/543bb40a-c8a6-11e6-82f0-b36146c704a6.png">

**All charts**
- [x] White cards behind each chart. We shouldn't need to change the way chart points are positioned, we can simply draw the card behind the chart--it's ok if the chart exceeds the bounds of the card.

**Line charts (eg weather)**
- [x] Min/max of graph based on the min/max values in the viewport
- [x] #73C1BA for all line charts besides symptoms/conditions
- [x] Horizontal lines to indicate the graph values, at regular intervals
The logic for deciding the values could be complex. The way I see it, we want them to be whole numbers at regular intervals, and we want the min/max lines to encapsulate all values on the chart. I'm open to suggestions for how to set up that behavior, or simplify it. This must be a solved problem due to all the charting libraries out there.

**Symptom/condition charts**
Same as line charts but:
- [x] Min/max fixed to 0-4 to match the rating system
- [x] Use the trackable color

**Based on [slack conversation](https://github.com/Flaredown/FlaredownEmber-2/issues/136#issuecomment-272806785)**:
- [x] treatment charts should be shorter because they just sit in a line
- [x] show decimal rulers if distance between whole rulers is less than 5

**Comment by mpugach** [comment]
should we also make onedimensional charts lower?

**Comment by mpugach** [comment]
> Min/max of graph based on the min/max values in the viewport

@lmerriam what do you mean?

**Comment by mpugach** [comment]
The log from Slack:

>**loganmerriam** [6:20 PM] 
for the question about min/max values: we want to set the top and bottom values of a given chart to encompass the greatest/least values that are visible on the chart for the current time period

>**mpugach** [6:23 PM] 
can we floor and ceil if they are float?

>**loganmerriam** [6:23 PM] 
so if i’m looking at a time period where humidity ranges from 62-72, we’d want a chart range that contains that range (for instance 60-75 would work) (edited)
[6:23]  
yes absolutely!

>**mpugach** [6:27 PM] 
should I also apply the this mockup on treatments charts? currently they are same hight as others and have different pin icon

>**loganmerriam** [6:33 PM] 
we may need to have an option for the chart component to set the number of decimals, because some measurements should be rounded to whole numbers, but some measurements are more sensitive
[6:34]  
yes treatment charts should be shorter because they just sit in a line
[6:34]  
as in the mockup
[6:34]  
they are basically fixed height

>**mpugach** [6:35 PM] 
Other charts are also fixed height )

>**loganmerriam** [6:35 PM] 
ha yes true
[6:36]  
was not thinking

>**mpugach** [6:39 PM] 
We show exact value on hover
What if we go to decimals only when the distance between whole is 1?
[6:39]  
Wait for screenshot

>**loganmerriam** [6:40 PM] 
sure, maybe a few more than 1
[6:40]  
<=5 maybe? (edited)
[6:41]  
at that point a .1 difference is 1/20th of the whole range so i think seeing decimals matters (edited)

>**mpugach** [6:43 PM] 
https://monosnap.com/file/1cFe6X9KVT2WElktmaHk0HBDpVTk22
[6:46]  
https://monosnap.com/file/knjpI40zjuIwiVhcsV3OPy3FhhC4LH

> **loganmerriam** [6:46 PM] 
yeah, definitely makes sense to have a detailed hover
[6:47]  
when you said
[6:47]  
>> What if we go to decimals only when the distance between whole is 1?

>[6:47]  
which labels were you referring to?

>**mpugach** [6:47 PM] 
the rulers

>**loganmerriam** [6:47 PM] 
ok
[6:48]  
yes let’s try the rule you proposed
[6:48]  
<1

>**mpugach** [6:48 PM] 
but if we want to show 5 rulers
[6:48]  
then “if distance is less than 5"

>**loganmerriam** [6:48 PM] 
yes, you’re right

**Comment by mpugach** [comment]
> #73C1BA for all line charts besides symptoms/conditions

@lmerriam did you mean for treatment also?

**Comment by lmerriam** [comment]
I guess what I should say is this: the *default* color for a chart should be our primary green color #73C1BA

So trackables that have assigned colors should override that color. Right now that's only symptoms, conditions and treatments.
