### ISSUE TITLE
Duplicate trackables in autosuggest

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#15]
See here:
<img width="465" alt="screenshot 2016-02-24 14 07 33" src="https://cloud.githubusercontent.com/assets/1657444/13297387/29ec91b8-db00-11e5-8f26-671b13ba3bee.png">

**Comment by algodave** [comment]
@lmerriam I just found in the database that you actually added `"Crohn's Disease"` 3 times as a new condition. 

``` ruby
params = ActionController::Parameters.new(resource: 'condition', query: { name: 'Crohn' })
search = Search.new(params)
ids = search.searchables.with_translations.map(&:id)
UserCondition.where(condition_id: ids).map { |uc| {uc.user.email => uc.condition.name} }
# I got:
# => [{"logan@flaredown.com"=>"Crohn's Disease"}, 
#     {"logan@flaredown.com"=>"Crohn's Disease"}, 
#     {"logan@flaredown.com"=>"Crohn's Disease"}]
```

Can you remember how you were able to do that in the UI? In the meanwhile I'll enforce a rule on the backend that no trackable can be added with the same name by the same user.

**Comment by lmerriam** [comment]
I think it's probably because I set up my account a few different times, when
you guys invited me to new versions and I went through onboarding again.

I think you already know this but just to make sure we're agreed: we want
everyone who adds Crohn's Disease (for example) to be tracking the same
condition from the database's point of view. When we do data aggregation we
need to know how many people have the illness and be able to find and group
users that way.

**Comment by algodave** [comment]
@lmerriam It seems to me that this:

> we want everyone who adds Crohn's Disease (for example) to be tracking the same
> condition from the database's point of view.

kind of conflicts with the following, grabbed from [Design Doc: Check-in](https://paper.dropbox.com/doc/Design-Doc-Check-in-JXiQVK4KzNL9p4R9zBFro)

> If users independently add a new trackable to the database 3 times, it should begin to appear in the autosuggest 

To meet the above, when 2 users independently add `"New Condition"`, those will actually be 2 different conditions on the database. Now I can easily fix to make them be the same when their name is equal (case insensitive), but in case of small differences or typos, they would be 2 different records.

We could later implement a "merge and cleanup" feature for an admin section of the app, as this has to be a human-supervised process IMO.

**Comment by lmerriam** [comment]
No problem, I am aware that small differences and typos will create different
records, there's really no way around that except (as you say) human-
supervised cleanup. It's annoying, but it won't be a blocking problem.

Could we still count two people independently typing in a condition together
if we check and see that the condition name is the same and count them as the
same record, and just make sure to not _display_ them in the autosuggest until
there are at least 3 (or more? don't know what the sweet spot would be) people
who have added it? That way it at least won't show people some of the typos,
or symptoms that only one person in the world is tracking -- even if they
exist (and they will)

Is all of that understandable? Complicated topic to communicate in typing

**Comment by algodave** [comment]
Sure, will move forward that way then

**Comment by lmerriam** [comment]
Also, out of curiosity, how much time do you think it would it take to migrate
the database of trackables we built in the original app?

**Comment by algodave** [comment]
Original app's seed data are there, we just pruned it because we're on heroku hobby. But with this commit: 1864efb61071eeaf938f4f778a8298bcc924eb15 they can **all** be loaded, as soon as we transfer the instance to you so that you can upgrade to a basic plan.
But perhaps you mean migrating current **live** data? (Which might include custom trackables added by current users)
In that case we need to create a ruby script to extract a JSON from current live database and import it into ours. I would suggest let's list **everything** we want to import from the current app, other than trackables, and then let's do the import one time only.

/cc @safeforge

**Comment by algodave** [comment]
@lmerriam I've fixed all duplicate issues, and also implemented logic to show trackables added more than N times. We can easily change N as it's a config: 
https://github.com/Flaredown/FlaredownEmber-2/blob/master/backend/config/initializers/00_app.rb#L29-L31
It will work on trackables added from now on.

Let's test it on [heroku](https://flaredown-webapp.herokuapp.com)
- I'll add "Coding Addiction" as a condition
- @safeforge @theworkerant @scottleyg please add "Coding Addiction" as a condition as well
- @lmerriam after everyone above has added that condition, you'll be able to see it in your dropdowns

Thanks guys for playing the game :)

**Comment by safeforge** [comment]
added!

**Comment by algodave** [comment]
@lmerriam I've checked the records and this is what I've found so far:
- Me and @safeforge have added "Coding Addiction", which has been recognized as being the same, so it has the same id (232)

``` ruby
UserCondition.where(condition_id: 232).map { |uc| {uc.user.email => uc.condition.name} }
# => [{"laquilareale@gmail.com"=>"Coding Addiction"}, 
#     {"salvatore.ferrucci@gmail.com"=>"Coding Addiction"}]
```
- @scottleyg has added "Coding Adiction", which has NOT been recognized as being the same because of one 'd' missing. 

``` ruby
UserCondition.where(condition_id: 233).map { |uc| {uc.user.email => uc.condition.name} }
# => [{"scottley35@gmail.com"=>"Coding Adiction"}]
```

Currently what I'm using is Postgres' `ILIKE` operator (case-insensitive LIKE), and we have just hit its limitation :-) 
On the other hand, however, I would not use to this purpose `pg_trgm`'s `similarity` function (the one we're using to return auto-suggest search results) because tolerance is difficult to tune for making it fit all cases, and it would end up considering the same 2 conditions which are actually different, e.g. 
- "Heart Disease", "Head Disease"

(just an example, don't know if they both actually exist!)

Coming to a conclusion, @lmerriam I think we have to accept that in case of typos, added trackables cannot be considered the same by the system; just what happened with "Coding Adiction" added by @scottleyg 

PS: Of course a more sophisticated algorithm (e.g. using a dictionary) would help, but I think such refinement is out of the current goals right?

**Comment by lmerriam** [comment]
Yep this is totally working as expected. Actually a good thing that it got misspelled so we could test that:) Did we not get @theworkerant 's record? He tried to add it too

**Comment by algodave** [comment]
He doesn't seem to have added any trackable:

``` ruby
graham = User.find_by(email: "graham@theworkerant.com")
UserCondition.where(user_id: graham.id).count
# => 0
UserSymptom.where(user_id: graham.id).count
# => 0
UserTreatment.where(user_id: graham.id).count
# => 0
```

**Comment by lmerriam** [comment]
:+1: resolved!
