### ISSUE TITLE
Harvey-Bradshaw Index

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#157]
The daily checkin is entirely driven by patients, which means they choose what they track. But sometimes we need to ask specific questions for research purposes. For our first test of this system, we should add the [Harvey Bradshaw Index](https://www.janssenmedicalinformation.ca/assets/pdf/HarveyBradshaw_English.pdf) (HBI) for Crohn's Disease. This is a short survey that doctors use which calculates a score for how active the user's disease is.

<img width="229" alt="screenshot 2017-02-14 23 57 05" src="https://cloud.githubusercontent.com/assets/1657444/22961362/6327a004-f313-11e6-8244-566310365733.png">
After calculating score:
<img width="270" alt="screenshot 2017-02-15 00 13 26" src="https://cloud.githubusercontent.com/assets/1657444/22961393/9939378e-f313-11e6-886e-00b3971229cb.png">

- [x] Unlike other trackables, HBI should only show up weekly. We should show this survey every day until the user completes it, at which point we should wait 1 week until we start showing it again. Because we don't want the user completing the survey in the past, ideally we should not show it on past days unless it was completed. I know this is fairly complicated logic, does this make sense?
- [x] Harvey Bradshaw Index delivered only to users with Crohn's Disease
- [x] [Calculate the score](https://www.janssenmedicalinformation.ca/assets/pdf/HarveyBradshaw_English.pdf) and save to the check-in as a trackable
- [x] Score is available on charts as `Crohn's Disease (Harvey Bradshaw Index)`

**Comment by lmerriam** [comment]
@mpugach this is top priority! Please let me know if you have questions or want to split this task up.

**Comment by mpugach** [comment]
1. we show the survey only if user tracks Crohn's Disease, right?
2. do we show our regular Crohn's Disease condition widget on everyday checkin?
3. how should checkin bottom navigation behave? I mean should the survey have own step or is it conditions step?
4. is the priority is higher then foods chart?

**Comment by mpugach** [comment]
5. Should we save user input before he hits "calculate"? We can save in local storage (per browser).

**Comment by mpugach** [comment]
6. Our charts are daily, how should we display weekly info?

**Comment by lmerriam** [comment]
1. Correct!
2. Yes, this won't override anything
3. This should be a section like other sections of the check-in, right before the summary. See wireframe below.
4. You can do these tasks in the order you prefer. If you want to close out the history stuff before moving to this, that's ok!
5. Yes I think we should save the answers like other trackables and 
6. It should still be part of a daily check-in, the user will need to come back to a day on which they completed it to see it, or they will see it today if it is due and they have not yet completed it.

![screenshot 2017-02-15 11 31 25](https://cloud.githubusercontent.com/assets/1657444/22984084/4c7b533c-f372-11e6-8442-68f9d0dc0d36.png)

**Comment by lmerriam** [comment]
FYI we will almost certainly have more surveys like this in the future, which will have the following properties:

- Delivered to a specific subset of users based on their trackables and/or demographic information
- An interval (daily, every 7 days, every 30 days, etc)
- A set of questions each with an input type that the user can respond with
- Some surveys will generate a score like the Harvey Bradshaw Index, some will not
- Each survey will likely have explanatory text like you see at the top of the HBI

**Comment by mpugach** [comment]
@lmerriam it is still in progress, but you can play with it on staging

todo:
- apply weekly rules
- show on charts
- fix "next" button labels for Health Factors and HBI

**Comment by lmerriam** [comment]
Looking really good so far! I'll try to style the calculated score card tomorrow if I get a chance, I know I only sent wireframes before.

**Comment by mpugach** [comment]
Can we place HBI step before Health Factors? Don't want to implement extra mess with dynamic "next" button label.

**Comment by lmerriam** [comment]
Even better, we can just remove the "review" button and use "next" for all sections except the last one. Since we no longer have a summary, we don't need to "review" anything.

**Comment by mpugach** [comment]
deployed to staging and removed old HBI data

**Comment by mpugach** [comment]
@lmerriam take a look please

**Comment by mpugach** [comment]
@lmerriam  I spent some efforts trying to make the HBI chart grid look nice. It is dynamic. Since we have no editing feature here are some screenshots for you:

![flaredown 2017-02-24 18-47-12](https://cloud.githubusercontent.com/assets/426179/23312587/fd5fa2b4-fac2-11e6-9719-3fb44b1834ad.jpg)
![flaredown 2017-02-24 18-48-13](https://cloud.githubusercontent.com/assets/426179/23312602/054519fa-fac3-11e6-9898-1d62c3867492.jpg)
![flaredown 2017-02-24 18-49-04](https://cloud.githubusercontent.com/assets/426179/23312605/0864b190-fac3-11e6-8a8e-27282a0c54d8.jpg)
![flaredown 2017-02-24 18-49-39](https://cloud.githubusercontent.com/assets/426179/23312611/0c89ec86-fac3-11e6-8542-348550fcd4ed.jpg)
![flaredown 2017-02-24 18-50-12](https://cloud.githubusercontent.com/assets/426179/23312615/11d0fbbc-fac3-11e6-8279-902463bb0451.jpg)
![flaredown 2017-02-24 18-50-41](https://cloud.githubusercontent.com/assets/426179/23312622/16cd9864-fac3-11e6-8b6d-2b8ca1f41422.jpg)
![flaredown 2017-02-24 18-51-16](https://cloud.githubusercontent.com/assets/426179/23312633/1d26bcea-fac3-11e6-9056-93c8c08f9f05.jpg)
![flaredown 2017-02-24 18-51-49](https://cloud.githubusercontent.com/assets/426179/23312639/21d66d8a-fac3-11e6-8f18-970a5704373b.jpg)
![flaredown 2017-02-24 18-52-24](https://cloud.githubusercontent.com/assets/426179/23312643/25052a32-fac3-11e6-8fc4-faee44beb616.jpg)

**Comment by lmerriam** [comment]
Really nice, max!

**Comment by lmerriam** [comment]
Is this same logic usable for other graph with a dynamic range?

**Comment by mpugach** [comment]
no, others have fixed rulers count

**Comment by mpugach** [comment]
but here it is strange to see decimal rulers

**Comment by mpugach** [comment]
@lmerriam are you sure we want long label here?
![flaredown 2017-03-01 11-12-10](https://cloud.githubusercontent.com/assets/426179/23453198/113efefa-fe70-11e6-9385-3e577014ed03.jpg)

**Comment by lmerriam** [comment]
No, I missed that! Maybe best to show score there, I am concerned if we show simply "remission" it could be considered medical advice. I made those labels longer mainly for the score screen to try to clarify that they are simply outputs of the HBI
