### ISSUE TITLE
Charts do not display on Android

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#169]
I can load the Flaredown app on both of my android phones (nexus 6p and nexus 5) but I cannot view the charts -- they are simply blank. If I open the website in the chrome browser on the same phones it works with no issues.

This appeared after the updates that added filtering.

![screenshot_20170127-211609](https://cloud.githubusercontent.com/assets/1657444/22393584/0c89e6ca-e4d7-11e6-80ce-3cc95e3c87b1.png)

**Comment by thunter1000** [comment]
Logan mentioned the issue and pointed out the solution on [stackoverflow](http://stackoverflow.com/questions/5899087/android-webview-localstorage/5934650#5934650). The issue was with the android application not allowing localstorage, which the graph relied on.

localstorage has now been enabled and a update has been published to the google playstore, which should be live within the next hour or so.

**Comment by lmerriam** [comment]
Fixed by @thunter1000
