### ISSUE TITLE
Do not create entry until user has entered data

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#19]
If the user is just navigating through days by clicking the back arrow, we don't want to create an entry for each one (and thus turn them into empty summaries) until they actually enter data to be saved.

**Comment by algodave** [comment]
@lmerriam I put checkin creation logic on the backend because I think it's safer. It basically initializes checkin with all currently tracked conditions and symptoms, with no values, and all currently tracked treatments, with a "not taken" state and their most recent dose if present in user's profile. I would like to keep this logic on the backend, so that it doesn't need to be replicated by mobile apps. 
With that said, individual checkin steps and summary screens on the Ember app are currently created based on an existing checkin record. So basically, if user is for example on symptoms step of today's checkin, and moves back to yesterday, the Ember app doesn't know which symptoms to show if checkin for that day doesn't exist yet.

So I think, if the actual issue is that you want to get rid of empty summaries, I would suggest we put in place one of the following logics:
- make the app aware of when a checkin is empty (i.e. user has never entered data in it) and, when user clicks on a day on the graph: if checkin is empty, show the checkin start screen; else, show the summary screen
- make the app aware of when a user has completed all checkin steps (i.e. for a given day, user has reached the checkin summary screen) and, when user clicks on a day on the graph, take him to the last step he completed, or to the summary if he completed all steps

Let me know what you think about my proposals.

**Comment by lmerriam** [comment]
Sounds good to me! First bullet point definitely, but I don't think we actually need to worry about the second one -- if someone decides to leave their check-in and come back later I'm fine with them completing it through the summary screen.

**Comment by algodave** [comment]
@lmerriam Implemented first solution, as per your suggestion
