### ISSUE TITLE
Charts show old trackables

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#200]
When I use a new device or browser and my history loads up, I see many trackables that I am not currently tracking. We should show only the trackables on the user's current check-in.

I believe there is a "user settings" object that keeps track of current trackables? That should be the list that the app defaults to when there are no cached chart settings.

**Comment by mpugach** [comment]
see the staging

if user loads charts on new device the charts for old trackables are hidden by default

this does not applies to foods and tags, because we can't be sure the user does not track them enymore

to check this, drop the cache in devtools console `localStorage.removeItem('chartsVisibilityV2')`

what is the next priority?

**Comment by lmerriam** [comment]
Works for me!

**Comment by mpugach** [comment]
I edited the text above

**Comment by lmerriam** [comment]
Regarding food and tags: I was expecting that and I believe it actually improves the experience. Tags and foods can easily crowd out the chart so it is better to have the user intentionally turn them on.

**Comment by mpugach** [comment]
pushed to staging

**Comment by lmerriam** [comment]
Ready to deploy
