### ISSUE TITLE
Posts visible to unauthenticated users

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#255]
The discussion is a great way for people to find Flaredown -- when patients search for answers online often the best results are forum threads started by other patients who experienced the same thing. Unauthenticated users should see a call to action to sign up for an account.

Unauthenticated users should see
- [x] Banner directing them to sign up for an account in order to join the discussion
- [x] No inputs to post/comment

- [x] We should add Facebook/Twitter/oEmbed metadata for sharing, with the title of the post and a preview of the content

**Comment by mpugach** [comment]
how should the banner look like?

**Comment by X-tina** [comment]
According to the issue, I have added:
- the first implementation of redirection unauthenticated users to sign up page (will you provide a banner?)
- conditional comment and reaction inputs
- added an ability to share title and post description to Facebook and Twitter

For the last point (oEmbed metadata), the task is time-consuming because it needed to be server rendered, but "fastboot" package conflicts with the current set of packages, need to debug deeply.

Could you please provide a priority for this?

**Comment by lmerriam** [comment]
@X-tina sounds good! Thank you for asking about oEmbed, it is definitely secondary, we should not do that for now.

Just to be clear: we don't want to automatically redirect users, we just want to give them a banner they can click on to be directed to the signup.

Here is a basic banner:
<img width="313" alt="screenshot 2017-06-01 01 02 17" src="https://cloud.githubusercontent.com/assets/1657444/26665228/2812c54c-4666-11e7-9fde-d3d8491d44f1.png">

On desktop it can look like this:
<img width="356" alt="screenshot 2017-06-01 01 07 44" src="https://cloud.githubusercontent.com/assets/1657444/26665311/bd3d295a-4666-11e7-9ce9-031b4eda38cb.png">

And while we're making changes to the template, it would be ideal to add content I added to the first mockup below the user comments (three circles and the button) to show the user why they should sign up. I will get images from a friend of mine who is an illustrator to replace the circles.

**Comment by lmerriam** [comment]
Good to go
