### ISSUE TITLE
Data export: Treatment without dosage not exported

### ISSUE THREAD

**Issue by compwron** [rubyforgood/Flaredown#406]
> I tried to export my data and realized it doesnt show my medications unless I put a dosage in. I thought turning the medication on was enough to record it, I didnt always record a dosage. Ive been using Flaredown for years and really dont want to lose all that data. Is there a way you can fix this so I can export the medication data without a dosage? Please get back to me.

**Comment by compwron** [comment]
This might be a real bug- worth investigating. Some screenshots of where this issue would be
"Download my data"
![Screen Shot 2021-10-08 at 4 52 30 PM](https://user-images.githubusercontent.com/578159/136635986-33a23688-9bd2-4800-b067-9bf297a8ab76.png)
![Screen Shot 2021-10-08 at 4 53 17 PM](https://user-images.githubusercontent.com/578159/136636022-e7bea587-9505-4cb2-9529-901c0320c703.png)

**Comment by bklang** [comment]
I am unable to reproduce this in my local environment. I created a checkin with 3 treatments: 1 active with dose, 1 active without dose, and 1 inactive. All 3 treatments appeared in my downloaded data.

**Comment by bklang** [comment]
Ah - now I see the issue: the treatment itself appears in the column headers, but there is no value in the CSV data for the associated field. In other words, there is no distinction between "no dose" and "disabled". We will need input from the application owners how they would like to see this data represented.

Suggestion: since the field is already unstructured, we could simply put a "1" in the field where the treatment is active, but recorded without a dose, and then put a "0" in the field when the treatment is inactive. Whenever a dose is recorded, we can put the recorded dose. This will allow distinguishing from days where the treatment was not recorded at all, in which cases the field will be empty.

**Comment by bklang** [comment]
Based on feedback from @lmerriam we are going to use "Taken" to indicate treatments received without a dosage, and "Not Taken" whenever the treatment is disabled in the UI.
