### ISSUE TITLE
Color of trackable too close to default gray color

### ISSUE THREAD

**Issue by squiggie** [rubyforgood/Flaredown#50]
The gray color of a trackable item is too close to the default color and could be mistaken for the items not being clickable/working. I actually thought something was wrong with the Back Pain trackable and it wasn't clickable when I first noticed it. See screen shot.

http://prntscr.com/amthgn

Consider either darkening the gray or not using a color so close to the default color.

**Comment by lmerriam** [comment]
Well that's a bug -- grey isn't one of our colors! I think maybe this trackable hasn't been assigned a color yet for some reason.

**Comment by lmerriam** [comment]
I got this too today:
<img width="587" alt="screenshot 2016-04-05 18 07 09" src="https://cloud.githubusercontent.com/assets/1657444/14299676/d4ac3b52-fb59-11e5-8e46-bffbb3cded9f.png">
<img width="1440" alt="screenshot 2016-04-05 18 18 39" src="https://cloud.githubusercontent.com/assets/1657444/14299998/b19fd9d2-fb5b-11e5-8242-5ef682ded41a.png">

Routing to the chart and back and refreshing the page did not fix.
The funny thing is that I added two new trackables within seconds, but only one the first one got this grey color. I wonder if this is the point at which colors start over and repeat, and there's some index mismatch?

**Comment by lmerriam** [comment]
Just added several trackables and got a lot of repeating of the same blue color:
<img width="545" alt="screenshot 2016-04-05 18 15 56" src="https://cloud.githubusercontent.com/assets/1657444/14299803/8dad6086-fb5a-11e5-9a12-6d6f72dd6613.png">

**Comment by lmerriam** [comment]
(This is not very high priority unless it is a simple fix)

**Comment by lmerriam** [comment]
Another user is seeing the issue: https://talk.flaredown.com/t/report-a-bug/135/103

**Comment by lmerriam** [comment]
Adding this to launch because multiple users are reporting it

**Comment by algodave** [comment]
@lmerriam I've fixed the root causes of the issue and now it works fine for new users who haven't done onboarding yet. In order to fix it for existing users, I need to run ad-hoc scripts to ensure that each trackable in their checkins has a different color than the others. To do so, I'll need to put the app in maintenance mode during this night (your time)

**Comment by lmerriam** [comment]
Nice! I'm fine with putting the app in maintenance.

**Comment by algodave** [comment]
@lmerriam Fixing colors on existing data in order to avoid duplications was a challenge, there might still be edge cases where duplicates are still there - e.g.: when all colors have been used on a user's trackables over time, repetition could happen within the same trackables' subgroup (e.g. conditions) 
A further optimization could be o avoid such repetition. I would suggest to fix individual cases that might happen as users report them, and open a new issue labeled as "enhancement" to tackle later.

**Comment by lmerriam** [comment]
Absolutely, that is the right call. I do not want to spend a lot of time fixing a few remaining cases if it's been fixed for users going forward.
