### ISSUE TITLE
Date issues

### ISSUE THREAD

**Issue by lmerriam** [rubyforgood/Flaredown#9]
Two issues I can reproduce:
- Clicking on a date on the graph takes me to the _prior_ day in the check-in
- Clicking the arrow to move to the previous day in the check-in moves me back two days, clicking the arrow to move to the next day in the check-in does not do anything

**Comment by algodave** [comment]
What could happen (although I didn't reproduce) is that checkin was created at a different date than the one passed by the client, because it was passing date with zulu-formatted time&zone info (which we actually don't need). In case of difference in date between the client and the server (due to time-zone) it could cause the above bugs.

@lmerriam Could you please make some tests and let me know? Also note: you might find some of your existing checkins in a different day than you were seeing before. As we don't matter about actual data at this stage, just let me know if the above flows are fixed and work as expected - thanks!

Also make sure you're clicking **once** when you move forward or backwards: consider that when no checkin exists in the previous/next day, it takes a bit more because it needs to be created (you can see  API calls in Network tab if you like). Of course we can optimize that and disable those buttons once the user has clicked, until the transition to the next/previous day completes.
